// T06 (v2.0.1-beta.2) — AI resilience chain end-to-end (phases 4–6).
//
// One test walks the full fallback story with REAL loopback HTTP:
// relay A refuses connections → relay B answers 500 → local Ollama-style
// server succeeds. onFallback records every hop, shouldStop aborts the chain
// between attempts, and the all-fail case lists every provider error.
//
// Deliberately NO TestWidgetsFlutterBinding — see the _MockHttpOverrides
// finding in test/api_key_rotation_service_test.dart.
import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:ghita_ppt_converter/providers/ai_provider_manager.dart';
import 'package:ghita_ppt_converter/services/api_fallback_cascade_service.dart';
import 'package:http/http.dart' as http;

AIProviderConfig _provider(String id, String name, String baseUrl,
        {String formatType = 'openai'}) =>
    AIProviderConfig(
      id: id,
      name: name,
      baseUrl: baseUrl,
      apiKey: 'sk-$id',
      availableModels: const ['test-model'],
      selectedModel: 'test-model',
      contextWindow: 8192,
      formatType: formatType,
    );

/// The generation task the cascade would run for real: a chat-completions
/// POST against the provider's own endpoint.
Future<String> _generateVia(http.Client client, AIProviderConfig config) async {
  final response = await client
      .post(
        Uri.parse('${config.baseUrl}/v1/chat/completions'),
        headers: {
          'Authorization': 'Bearer ${config.apiKey}',
          'Content-Type': 'application/json',
        },
        body: jsonEncode({
          'model': config.selectedModel,
          'messages': [
            {'role': 'user', 'content': 'Generate slide HTML'}
          ],
        }),
      )
      .timeout(const Duration(seconds: 10));
  if (response.statusCode != 200) {
    throw Exception('HTTP ${response.statusCode} from ${config.name}');
  }
  final data = jsonDecode(response.body) as Map<String, dynamic>;
  final choices = data['choices'] as List;
  return (choices.first['message']['content'] ?? '').toString();
}

void main() {
  late HttpServer ollama;
  var ollamaHits = 0;

  setUp(() async {
    ollamaHits = 0;
    // Local "Ollama": always answers with a valid completion.
    ollama = await HttpServer.bind(InternetAddress.loopbackIPv4, 0);
    ollama.listen((request) async {
      await request.drain<void>();
      ollamaHits++;
      request.response.headers.contentType = ContentType.json;
      request.response.add(utf8.encode(jsonEncode({
        'choices': [
          {
            'message': {
              'content': '<h1>Generated by local model</h1>'
            }
          }
        ]
      })));
      await request.response.close();
    });
  });

  tearDown(() async {
    await ollama.close(force: true);
  });

  AIProviderConfig localOllama() => _provider(
      'local', 'Ollama (Local)', "http://127.0.0.1:${ollama.port}");

  group('full resilience chain', () {
    test('dead relay → 500 relay → local model, with fallback breadcrumbs',
        () async {
      // Relay A: nothing listens there (connection refused).
      final dead = await HttpServer.bind(InternetAddress.loopbackIPv4, 0);
      final deadPort = dead.port;
      await dead.close(force: true);
      final relayA = _provider('relay-a', 'Relay A', 'http://127.0.0.1:$deadPort');

      // Relay B: always 500 (quota / key exhausted).
      final relayBServer =
          await HttpServer.bind(InternetAddress.loopbackIPv4, 0);
      var relayBHits = 0;
      relayBServer.listen((request) async {
        await request.drain<void>();
        relayBHits++;
        request.response.statusCode = 500;
        await request.response.close();
      });
      final relayB = _provider('relay-b', 'Relay B',
          'http://127.0.0.1:${relayBServer.port}');
      final client = http.Client();

      final fallbacks = <String>[];
      final cascade = APIFallbackCascadeService();
      final html = await cascade.executeWithFallback<String>(
        [relayA, relayB, localOllama()],
        (config) => _generateVia(client, config),
        onFallback: (failed, error, attempt) =>
            fallbacks.add("${failed.name}#$attempt"),
      );

      expect(html, contains('local model'));
      expect(fallbacks, ['Relay A#1', 'Relay B#2'],
          reason: 'every failed hop is reported before moving on');
      expect(relayBHits, 1);
      expect(ollamaHits, 1);

      client.close();
      await relayBServer.close(force: true);
    });

    test('shouldStop aborts the chain between attempts', () async {
      final dead = await HttpServer.bind(InternetAddress.loopbackIPv4, 0);
      final deadPort = dead.port;
      await dead.close(force: true);

      var stop = false;
      final cascade = APIFallbackCascadeService();
      await expectLater(
        cascade.executeWithFallback<String>(
          [
            _provider('a', 'First', 'http://127.0.0.1:$deadPort'),
            localOllama(),
          ],
          (config) => _generateVia(http.Client(), config),
          shouldStop: () => stop || true, // Stop pressed up-front.
        ),
        throwsA(predicate((e) =>
            e.toString().contains('stopped by the user'))),
      );
      expect(ollamaHits, 0,
          reason: 'a stopped chain must not touch remaining providers');
    });

    test('all providers failing surfaces every error in one exception',
        () async {
      final dead1 = await HttpServer.bind(InternetAddress.loopbackIPv4, 0);
      final port1 = dead1.port;
      await dead1.close(force: true);
      final dead2 = await HttpServer.bind(InternetAddress.loopbackIPv4, 0);
      final port2 = dead2.port;
      await dead2.close(force: true);

      final cascade = APIFallbackCascadeService();
      await expectLater(
        cascade.executeWithFallback<String>(
          [
            _provider('x', 'Dead One', 'http://127.0.0.1:$port1'),
            _provider('y', 'Dead Two', 'http://127.0.0.1:$port2'),
          ],
          (config) => _generateVia(http.Client(), config),
        ),
        throwsA(predicate((e) =>
            e.toString().contains('Dead One') &&
            e.toString().contains('Dead Two'))),
      );
      expect(ollamaHits, 0);
    });
  });
}
