/// Symbol library service (Track 18, FEAT 19).
///
/// Categorized Unicode symbols (currency, arrows, math, technical, Greek,
/// emoji) plus a search-by-code-point function. Each symbol has a label,
/// character, and category.
library;

class SymbolItem {
  const SymbolItem({
    required this.char,
    required this.name,
    required this.category,
  });

  final String char;
  final String name;
  final String category;
}

class SymbolService {
  SymbolService._();

  static Map<String, List<SymbolItem>> get byCategory {
    if (_cache != null) return _cache!;
    _cache = _buildIndex(_all);
    return _cache!;
  }

  static Map<String, List<SymbolItem>>? _cache;

  static List<SymbolItem> search(String query) {
    if (query.trim().isEmpty) return _all;
    final q = query.toLowerCase();
    return _all.where((s) =>
        s.name.toLowerCase().contains(q) ||
        s.char.contains(q) ||
        s.category.toLowerCase().contains(q)).toList();
  }

  static Map<String, List<SymbolItem>> _buildIndex(List<SymbolItem> items) {
    final map = <String, List<SymbolItem>>{};
    for (final item in items) {
      map.putIfAbsent(item.category, () => []).add(item);
    }
    return map;
  }

  static final List<SymbolItem> _all = [
    // ---- Currency ----------------------------------------------------------
    const SymbolItem(char: '\$', name: 'Dollar', category: 'Currency'),
    const SymbolItem(char: '€', name: 'Euro', category: 'Currency'),
    const SymbolItem(char: '£', name: 'Pound', category: 'Currency'),
    const SymbolItem(char: '¥', name: 'Yen', category: 'Currency'),
    const SymbolItem(char: '₫', name: 'Dong', category: 'Currency'),
    const SymbolItem(char: '₽', name: 'Ruble', category: 'Currency'),
    const SymbolItem(char: '₩', name: 'Won', category: 'Currency'),
    const SymbolItem(char: '₹', name: 'Rupee', category: 'Currency'),
    const SymbolItem(char: '₺', name: 'Lira', category: 'Currency'),
    const SymbolItem(char: '₿', name: 'Bitcoin', category: 'Currency'),

    // ---- Arrows ------------------------------------------------------------
    const SymbolItem(char: '←', name: 'Left Arrow', category: 'Arrows'),
    const SymbolItem(char: '→', name: 'Right Arrow', category: 'Arrows'),
    const SymbolItem(char: '↑', name: 'Up Arrow', category: 'Arrows'),
    const SymbolItem(char: '↓', name: 'Down Arrow', category: 'Arrows'),
    const SymbolItem(char: '↔', name: 'Left-Right Arrow', category: 'Arrows'),
    const SymbolItem(char: '↕', name: 'Up-Down Arrow', category: 'Arrows'),
    const SymbolItem(char: '⇐', name: 'Double Left', category: 'Arrows'),
    const SymbolItem(char: '⇒', name: 'Double Right', category: 'Arrows'),
    const SymbolItem(char: '⇑', name: 'Double Up', category: 'Arrows'),
    const SymbolItem(char: '⇓', name: 'Double Down', category: 'Arrows'),
    const SymbolItem(char: '↵', name: 'Return', category: 'Arrows'),
    const SymbolItem(char: '↩', name: 'Left Hook', category: 'Arrows'),
    const SymbolItem(char: '↪', name: 'Right Hook', category: 'Arrows'),
    const SymbolItem(char: '↻', name: 'Clockwise', category: 'Arrows'),
    const SymbolItem(char: '↺', name: 'Counterclockwise', category: 'Arrows'),
    const SymbolItem(char: '➔', name: 'Heavy Right', category: 'Arrows'),
    const SymbolItem(char: '➢', name: 'Triangular Right', category: 'Arrows'),
    const SymbolItem(char: '⏩', name: 'Fast Forward', category: 'Arrows'),
    const SymbolItem(char: '⏪', name: 'Rewind', category: 'Arrows'),
    const SymbolItem(char: '⏫', name: 'Fast Up', category: 'Arrows'),
    const SymbolItem(char: '⏬', name: 'Fast Down', category: 'Arrows'),

    // ---- Math --------------------------------------------------------------
    const SymbolItem(char: '±', name: 'Plus-Minus', category: 'Math'),
    const SymbolItem(char: '×', name: 'Multiply', category: 'Math'),
    const SymbolItem(char: '÷', name: 'Divide', category: 'Math'),
    const SymbolItem(char: '≈', name: 'Approximately', category: 'Math'),
    const SymbolItem(char: '≠', name: 'Not Equal', category: 'Math'),
    const SymbolItem(char: '≡', name: 'Identical', category: 'Math'),
    const SymbolItem(char: '≤', name: 'Less or Equal', category: 'Math'),
    const SymbolItem(char: '≥', name: 'Greater or Equal', category: 'Math'),
    const SymbolItem(char: '∞', name: 'Infinity', category: 'Math'),
    const SymbolItem(char: '∑', name: 'Sum', category: 'Math'),
    const SymbolItem(char: '∏', name: 'Product', category: 'Math'),
    const SymbolItem(char: '∫', name: 'Integral', category: 'Math'),
    const SymbolItem(char: '∮', name: 'Contour Integral', category: 'Math'),
    const SymbolItem(char: '∂', name: 'Partial Differential', category: 'Math'),
    const SymbolItem(char: '∆', name: 'Increment', category: 'Math'),
    const SymbolItem(char: '√', name: 'Square Root', category: 'Math'),
    const SymbolItem(char: '∛', name: 'Cube Root', category: 'Math'),
    const SymbolItem(char: '∠', name: 'Angle', category: 'Math'),
    const SymbolItem(char: '⊥', name: 'Perpendicular', category: 'Math'),
    const SymbolItem(char: '∡', name: 'Measured Angle', category: 'Math'),
    const SymbolItem(char: '∩', name: 'Intersection', category: 'Math'),
    const SymbolItem(char: '∪', name: 'Union', category: 'Math'),
    const SymbolItem(char: '∧', name: 'Logical And', category: 'Math'),
    const SymbolItem(char: '∨', name: 'Logical Or', category: 'Math'),
    const SymbolItem(char: '¬', name: 'Not', category: 'Math'),
    const SymbolItem(char: '∀', name: 'For All', category: 'Math'),
    const SymbolItem(char: '∃', name: 'There Exists', category: 'Math'),
    const SymbolItem(char: '∅', name: 'Empty Set', category: 'Math'),
    const SymbolItem(char: '∈', name: 'Element Of', category: 'Math'),
    const SymbolItem(char: '∉', name: 'Not Element', category: 'Math'),
    const SymbolItem(char: '⊂', name: 'Subset', category: 'Math'),
    const SymbolItem(char: '⊃', name: 'Superset', category: 'Math'),
    const SymbolItem(char: '⊆', name: 'Subset or Equal', category: 'Math'),
    const SymbolItem(char: '⊇', name: 'Superset or Equal', category: 'Math'),
    const SymbolItem(char: '⊕', name: 'Circled Plus', category: 'Math'),
    const SymbolItem(char: '⊗', name: 'Circled Times', category: 'Math'),
    const SymbolItem(char: 'α', name: 'Alpha', category: 'Greek'),
    const SymbolItem(char: 'β', name: 'Beta', category: 'Greek'),
    const SymbolItem(char: 'γ', name: 'Gamma', category: 'Greek'),
    const SymbolItem(char: 'δ', name: 'Delta', category: 'Greek'),
    const SymbolItem(char: 'ε', name: 'Epsilon', category: 'Greek'),
    const SymbolItem(char: 'ζ', name: 'Zeta', category: 'Greek'),
    const SymbolItem(char: 'η', name: 'Eta', category: 'Greek'),
    const SymbolItem(char: 'θ', name: 'Theta', category: 'Greek'),
    const SymbolItem(char: 'ι', name: 'Iota', category: 'Greek'),
    const SymbolItem(char: 'κ', name: 'Kappa', category: 'Greek'),
    const SymbolItem(char: 'λ', name: 'Lambda', category: 'Greek'),
    const SymbolItem(char: 'μ', name: 'Mu', category: 'Greek'),
    const SymbolItem(char: 'ν', name: 'Nu', category: 'Greek'),
    const SymbolItem(char: 'ξ', name: 'Xi', category: 'Greek'),
    const SymbolItem(char: 'ο', name: 'Omicron', category: 'Greek'),
    const SymbolItem(char: 'π', name: 'Pi', category: 'Greek'),
    const SymbolItem(char: 'ρ', name: 'Rho', category: 'Greek'),
    const SymbolItem(char: 'σ', name: 'Sigma', category: 'Greek'),
    const SymbolItem(char: 'τ', name: 'Tau', category: 'Greek'),
    const SymbolItem(char: 'υ', name: 'Upsilon', category: 'Greek'),
    const SymbolItem(char: 'φ', name: 'Phi', category: 'Greek'),
    const SymbolItem(char: 'χ', name: 'Chi', category: 'Greek'),
    const SymbolItem(char: 'ψ', name: 'Psi', category: 'Greek'),
    const SymbolItem(char: 'ω', name: 'Omega', category: 'Greek'),
    const SymbolItem(char: 'Α', name: 'Alpha Capital', category: 'Greek'),
    const SymbolItem(char: 'Β', name: 'Beta Capital', category: 'Greek'),
    const SymbolItem(char: 'Γ', name: 'Gamma Capital', category: 'Greek'),
    const SymbolItem(char: 'Δ', name: 'Delta Capital', category: 'Greek'),
    const SymbolItem(char: 'Θ', name: 'Theta Capital', category: 'Greek'),
    const SymbolItem(char: 'Λ', name: 'Lambda Capital', category: 'Greek'),
    const SymbolItem(char: 'Ξ', name: 'Xi Capital', category: 'Greek'),
    const SymbolItem(char: 'Π', name: 'Pi Capital', category: 'Greek'),
    const SymbolItem(char: 'Σ', name: 'Sigma Capital', category: 'Greek'),
    const SymbolItem(char: 'Φ', name: 'Phi Capital', category: 'Greek'),
    const SymbolItem(char: 'Ψ', name: 'Psi Capital', category: 'Greek'),
    const SymbolItem(char: 'Ω', name: 'Omega Capital', category: 'Greek'),

    // ---- Technical ---------------------------------------------------------
    const SymbolItem(char: '°', name: 'Degree', category: 'Technical'),
    const SymbolItem(char: '′', name: 'Prime', category: 'Technical'),
    const SymbolItem(char: '″', name: 'Double Prime', category: 'Technical'),
    const SymbolItem(char: '‰', name: 'Per Mille', category: 'Technical'),
    const SymbolItem(char: '§', name: 'Section', category: 'Technical'),
    const SymbolItem(char: '¶', name: 'Pilcrow', category: 'Technical'),
    const SymbolItem(char: '†', name: 'Dagger', category: 'Technical'),
    const SymbolItem(char: '‡', name: 'Double Dagger', category: 'Technical'),
    const SymbolItem(char: '©', name: 'Copyright', category: 'Technical'),
    const SymbolItem(char: '®', name: 'Registered', category: 'Technical'),
    const SymbolItem(char: '™', name: 'Trademark', category: 'Technical'),
    const SymbolItem(char: '℠', name: 'Service Mark', category: 'Technical'),
    const SymbolItem(char: '℗', name: 'Sound Recording', category: 'Technical'),
    const SymbolItem(char: '‰', name: 'Per Mille', category: 'Technical'),
    const SymbolItem(char: '‱', name: 'Per Ten Thousand', category: 'Technical'),
    const SymbolItem(char: '№', name: 'Numero', category: 'Technical'),
    const SymbolItem(char: '℡', name: 'Telephone', category: 'Technical'),
    const SymbolItem(char: '℻', name: 'Fax', category: 'Technical'),
    const SymbolItem(char: '⅓', name: 'One Third', category: 'Technical'),
    const SymbolItem(char: '⅔', name: 'Two Thirds', category: 'Technical'),
    const SymbolItem(char: '⅕', name: 'One Fifth', category: 'Technical'),
    const SymbolItem(char: '⅖', name: 'Two Fifths', category: 'Technical'),
    const SymbolItem(char: '⅗', name: 'Three Fifths', category: 'Technical'),
    const SymbolItem(char: '⅘', name: 'Four Fifths', category: 'Technical'),
    const SymbolItem(char: '⅙', name: 'One Sixth', category: 'Technical'),
    const SymbolItem(char: '⅚', name: 'Five Sixths', category: 'Technical'),
    const SymbolItem(char: '⅛', name: 'One Eighth', category: 'Technical'),
    const SymbolItem(char: '⅜', name: 'Three Eighths', category: 'Technical'),
    const SymbolItem(char: '⅝', name: 'Five Eighths', category: 'Technical'),
    const SymbolItem(char: '⅞', name: 'Seven Eighths', category: 'Technical'),

    // ---- Emoji / Misc ------------------------------------------------------
    const SymbolItem(char: '✓', name: 'Checkmark', category: 'Misc'),
    const SymbolItem(char: '✗', name: 'Cross', category: 'Misc'),
    const SymbolItem(char: '★', name: 'Star Filled', category: 'Misc'),
    const SymbolItem(char: '☆', name: 'Star Outline', category: 'Misc'),
    const SymbolItem(char: '♥', name: 'Heart', category: 'Misc'),
    const SymbolItem(char: '♦', name: 'Diamond', category: 'Misc'),
    const SymbolItem(char: '♣', name: 'Club', category: 'Misc'),
    const SymbolItem(char: '♠', name: 'Spade', category: 'Misc'),
    const SymbolItem(char: '▪', name: 'Square Filled', category: 'Misc'),
    const SymbolItem(char: '▫', name: 'Square Outline', category: 'Misc'),
    const SymbolItem(char: '●', name: 'Circle Filled', category: 'Misc'),
    const SymbolItem(char: '○', name: 'Circle Outline', category: 'Misc'),
    const SymbolItem(char: '◆', name: 'Diamond Filled', category: 'Misc'),
    const SymbolItem(char: '◇', name: 'Diamond Outline', category: 'Misc'),
    const SymbolItem(char: '☰', name: 'Trigram', category: 'Misc'),
    const SymbolItem(char: '☺', name: 'Smiley', category: 'Misc'),
    const SymbolItem(char: '☹', name: 'Frown', category: 'Misc'),
    const SymbolItem(char: '☻', name: 'Smiley Filled', category: 'Misc'),
    const SymbolItem(char: '⚑', name: 'Flag', category: 'Misc'),
    const SymbolItem(char: '⚐', name: 'Flag Outline', category: 'Misc'),
    const SymbolItem(char: '⚠', name: 'Warning', category: 'Misc'),
    const SymbolItem(char: '⚡', name: 'High Voltage', category: 'Misc'),
    const SymbolItem(char: '♻', name: 'Recycling', category: 'Misc'),
    const SymbolItem(char: '✉', name: 'Envelope', category: 'Misc'),
    const SymbolItem(char: '✎', name: 'Pencil', category: 'Misc'),
    const SymbolItem(char: '✏', name: 'Pencil Solid', category: 'Misc'),
    const SymbolItem(char: '✂', name: 'Scissors', category: 'Misc'),
    const SymbolItem(char: '🔒', name: 'Lock', category: 'Misc'),
    const SymbolItem(char: '🔓', name: 'Unlock', category: 'Misc'),
    const SymbolItem(char: '🔑', name: 'Key', category: 'Misc'),
    const SymbolItem(char: '🔍', name: 'Magnifier', category: 'Misc'),
    const SymbolItem(char: '🔎', name: 'Magnifier Right', category: 'Misc'),
    const SymbolItem(char: '💡', name: 'Bulb', category: 'Misc'),
    const SymbolItem(char: '📌', name: 'Pin', category: 'Misc'),
    const SymbolItem(char: '📍', name: 'Round Pin', category: 'Misc'),
    const SymbolItem(char: '📎', name: 'Paperclip', category: 'Misc'),
    const SymbolItem(char: '📏', name: 'Ruler', category: 'Misc'),
    const SymbolItem(char: '📐', name: 'Triangular Ruler', category: 'Misc'),
    const SymbolItem(char: '📊', name: 'Chart', category: 'Misc'),
    const SymbolItem(char: '📈', name: 'Chart Rising', category: 'Misc'),
    const SymbolItem(char: '📉', name: 'Chart Falling', category: 'Misc'),
    const SymbolItem(char: '📋', name: 'Clipboard', category: 'Misc'),
    const SymbolItem(char: '📁', name: 'Folder', category: 'Misc'),
    const SymbolItem(char: '📂', name: 'Folder Open', category: 'Misc'),
    const SymbolItem(char: '🖨', name: 'Printer', category: 'Misc'),
    const SymbolItem(char: '🖥', name: 'Monitor', category: 'Misc'),
    const SymbolItem(char: '🖱', name: 'Mouse', category: 'Misc'),
    const SymbolItem(char: '🖲', name: 'Trackball', category: 'Misc'),
    const SymbolItem(char: '🗂', name: 'Card Index', category: 'Misc'),
    const SymbolItem(char: '🗑', name: 'Trash', category: 'Misc'),
    const SymbolItem(char: '🗓', name: 'Calendar', category: 'Misc'),
    const SymbolItem(char: '🕐', name: 'Clock', category: 'Misc'),
    const SymbolItem(char: '🕒', name: 'Clock 3', category: 'Misc'),
    const SymbolItem(char: '🕕', name: 'Clock 6', category: 'Misc'),
    const SymbolItem(char: '🕘', name: 'Clock 9', category: 'Misc'),
    const SymbolItem(char: '🕛', name: 'Clock 12', category: 'Misc'),
    const SymbolItem(char: '🗺', name: 'World Map', category: 'Misc'),
    const SymbolItem(char: '🗨', name: 'Speech Bubble', category: 'Misc'),
    const SymbolItem(char: '🗯', name: 'Angry Bubble', category: 'Misc'),
    const SymbolItem(char: '🖐', name: 'Hand', category: 'Misc'),
    const SymbolItem(char: '✋', name: 'Hand Raised', category: 'Misc'),
    const SymbolItem(char: '☝', name: 'Index Point', category: 'Misc'),
    const SymbolItem(char: '👆', name: 'Index Up', category: 'Misc'),
    const SymbolItem(char: '👇', name: 'Index Down', category: 'Misc'),
    const SymbolItem(char: '👈', name: 'Index Left', category: 'Misc'),
    const SymbolItem(char: '👉', name: 'Index Right', category: 'Misc'),
    const SymbolItem(char: '👌', name: 'OK Hand', category: 'Misc'),
    const SymbolItem(char: '👍', name: 'Thumbs Up', category: 'Misc'),
    const SymbolItem(char: '👎', name: 'Thumbs Down', category: 'Misc'),
    const SymbolItem(char: '👏', name: 'Clapping', category: 'Misc'),
    const SymbolItem(char: '🙌', name: 'Raising Hands', category: 'Misc'),
    const SymbolItem(char: '🤝', name: 'Handshake', category: 'Misc'),
    const SymbolItem(char: '💪', name: 'Flexed Arm', category: 'Misc'),
    const SymbolItem(char: '🧠', name: 'Brain', category: 'Misc'),
    const SymbolItem(char: '👀', name: 'Eyes', category: 'Misc'),
    const SymbolItem(char: '👁', name: 'Eye', category: 'Misc'),
    const SymbolItem(char: '👃', name: 'Nose', category: 'Misc'),
    const SymbolItem(char: '👄', name: 'Mouth', category: 'Misc'),
    const SymbolItem(char: '💬', name: 'Speech Balloon', category: 'Misc'),
    const SymbolItem(char: '💭', name: 'Thought Balloon', category: 'Misc'),
    const SymbolItem(char: '💤', name: 'ZZZ', category: 'Misc'),
    const SymbolItem(char: '💢', name: 'Anger', category: 'Misc'),
    const SymbolItem(char: '💣', name: 'Bomb', category: 'Misc'),
    const SymbolItem(char: '💥', name: 'Collision', category: 'Misc'),
    const SymbolItem(char: '💦', name: 'Sweat Drops', category: 'Misc'),
    const SymbolItem(char: '💨', name: 'Dashing', category: 'Misc'),
    const SymbolItem(char: '💫', name: 'Dizzy', category: 'Misc'),
    const SymbolItem(char: '💬', name: 'Speech Balloon', category: 'Misc'),
    const SymbolItem(char: '🔥', name: 'Fire', category: 'Misc'),
    const SymbolItem(char: '⭐', name: 'Star Glow', category: 'Misc'),
    const SymbolItem(char: '🌟', name: 'Star Glitter', category: 'Misc'),
    const SymbolItem(char: '✨', name: 'Sparkles', category: 'Misc'),
    const SymbolItem(char: '💯', name: '100', category: 'Misc'),
  ];
}