// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `add_block`, `append_row`, `attr_bool`, `attr_str`, `children_of`, `class_contains`, `collapse_ws`, `css_align_to_algn`, `css_color_names`, `css_color_to_hex`, `css_font_size_to_sz`, `elem_is_tag_any`, `elem_is`, `extract_blocks_inner`, `extract_blocks`, `extract_inline_paragraphs`, `extract_table`, `find_elem_ref`, `find_elem`, `flush_list`, `flush_paragraphs`, `is_text_node`, `is_ws`, `local_tag`, `make_run`, `merge_style`, `new`, `prepare_run_group`, `remove_from_tree`, `text_of_first_elem`, `text_of`, `try_parse`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BlockStream`

/// One-shot entry: parse [html] and return the four artifacts the session
/// parse cache needs (blocks / blocksNoFirstH2 / notes / subtitle) as a JSON
/// object. html5ever is always-recovering, so errors are rare; when one does
/// surface the Dart facade falls back to the Dart parser.
String htmlparseBlocks({required String html}) =>
    RustLib.instance.api.crateApiHtmlparseHtmlparseBlocks(html: html);
