// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `encode_jpeg`, `has_alpha`, `normalize_ext`, `orientation_from_jpeg`, `orientation_from_png`, `orientation_from_tag`, `orientation_from_tiff`, `read_exif_orientation`

/// Process one image. Errors never panic: a decode failure returns Err and
/// the Dart facade falls back (or records the warning like the Dart path).
/// `#[frb(sync)]`: the Dart facade must stay synchronous — it is called from
/// the export generation hot path (like the Dart `image` implementation it
/// replaces on the engine path).
ImageOpResult imgProcess({required ImageJob job}) =>
    RustLib.instance.api.crateApiImageImgProcess(job: job);

/// Process a batch in parallel (used by N2 optimizer exports).
Future<List<ImageOpResult>> imgProcessBatch({required List<ImageJob> jobs}) =>
    RustLib.instance.api.crateApiImageImgProcessBatch(jobs: jobs);

/// SHA-256 of arbitrary bytes — media dedupe / cache keys (T06 phase 9).
String imgSha256({required List<int> bytes}) =>
    RustLib.instance.api.crateApiImageImgSha256(bytes: bytes);

/// One image job: the raw bytes plus the processing options.
class ImageJob {
  final Uint8List bytes;

  /// "png" | "jpg" | "gif" (normalized; jpeg → jpg).
  final String ext;

  /// Downscale width; <= 0 means no resize.
  final PlatformInt64 maxWidth;

  /// Allow PNG → JPEG re-encode for large opaque images.
  final bool allowJpeg;

  /// JPEG quality used by every re-encode (1..=100).
  final PlatformInt64 jpegQuality;

  const ImageJob({
    required this.bytes,
    required this.ext,
    required this.maxWidth,
    required this.allowJpeg,
    required this.jpegQuality,
  });

  @override
  int get hashCode =>
      bytes.hashCode ^
      ext.hashCode ^
      maxWidth.hashCode ^
      allowJpeg.hashCode ^
      jpegQuality.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageJob &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          ext == other.ext &&
          maxWidth == other.maxWidth &&
          allowJpeg == other.allowJpeg &&
          jpegQuality == other.jpegQuality;
}

/// Result of one processed image, mirroring Dart `LoadedImage`.
class ImageOpResult {
  final Uint8List bytes;

  /// "png" | "jpg" | "gif" of the OUTPUT bytes.
  final String ext;
  final int width;
  final int height;

  /// Whether the output bytes differ from the input (passthrough == false).
  final bool changed;

  /// Whether the image was downscaled (drives the Dart-side savings tally).
  final bool resized;

  const ImageOpResult({
    required this.bytes,
    required this.ext,
    required this.width,
    required this.height,
    required this.changed,
    required this.resized,
  });

  @override
  int get hashCode =>
      bytes.hashCode ^
      ext.hashCode ^
      width.hashCode ^
      height.hashCode ^
      changed.hashCode ^
      resized.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageOpResult &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          ext == other.ext &&
          width == other.width &&
          height == other.height &&
          changed == other.changed &&
          resized == other.resized;
}
