// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Build a ZIP archive from [ZipEntry] list, returning the archive bytes.
///
/// `level` is the deflate level for text entries (0 disables deflate).
/// Deterministic: the same entries produce byte-identical output, which keeps
/// the existing .ghita/PPTX hash/verification behavior intact.
Future<Uint8List> zipArchive(
        {required List<ZipEntry> entries, required PlatformInt64 level}) =>
    RustLib.instance.api.crateApiZipZipArchive(entries: entries, level: level);

/// One member of the archive. `stored: true` writes the bytes without a
/// second deflate pass (media arrives already compressed).
class ZipEntry {
  final String name;
  final Uint8List data;
  final bool stored;

  const ZipEntry({
    required this.name,
    required this.data,
    required this.stored,
  });

  @override
  int get hashCode => name.hashCode ^ data.hashCode ^ stored.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZipEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          data == other.data &&
          stored == other.stored;
}
